=begin
#Onfido Public API v3.6

#The Onfido Public API (v3.6)

The version of the OpenAPI document: v3.6

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

module Onfido
  VERSION = '5.5.0'
end
