=begin
#Onfido Public API v3.6

#The Onfido Public API (v3.6)

The version of the OpenAPI document: v3.6

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module Onfido
  class CheckStatus
    IN_PROGRESS = "in_progress".freeze
    AWAITING_APPLICANT = "awaiting_applicant".freeze
    COMPLETE = "complete".freeze
    WITHDRAWN = "withdrawn".freeze
    PAUSED = "paused".freeze
    REOPENED = "reopened".freeze
    UNKNOWN_DEFAULT_OPEN_API = "unknown_default_open_api".freeze

    def self.all_vars
      @all_vars ||= [IN_PROGRESS, AWAITING_APPLICANT, COMPLETE, WITHDRAWN, PAUSED, REOPENED, UNKNOWN_DEFAULT_OPEN_API].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CheckStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CheckStatus"
    end
  end
end
