=begin
#Onfido API v3.6

#The Onfido API (v3.6)

The version of the OpenAPI document: v3.6

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Onfido
  class DocumentTypes
    PASSPORT = "passport".freeze
    DRIVING_LICENCE = "driving_licence".freeze
    NATIONAL_IDENTITY_CARD = "national_identity_card".freeze
    RESIDENCE_PERMIT = "residence_permit".freeze
    PASSPORT_CARD = "passport_card".freeze
    TAX_ID = "tax_id".freeze
    VISA = "visa".freeze
    VOTER_ID = "voter_id".freeze
    RESIDENCE_STATUS_DOCUMENT = "residence_status_document".freeze
    POSTAL_IDENTITY_CARD = "postal_identity_card".freeze
    SOCIAL_SECURITY_CARD = "social_security_card".freeze
    WORK_PERMIT = "work_permit".freeze
    ASYLUM_REGISTRATION_CARD = "asylum_registration_card".freeze
    NATIONAL_HEALTH_INSURANCE_CARD = "national_health_insurance_card".freeze
    MUNICIPALITY_IDENTITY_CARD = "municipality_identity_card".freeze
    PRIVATE_OPERATORS_CARD = "private_operators_card".freeze
    PROOF_OF_CITIZENSHIP = "proof_of_citizenship".freeze
    SERVICE_ID_CARD = "service_id_card".freeze
    IMMIGRATION_STATUS_DOCUMENT = "immigration_status_document".freeze
    INDIGENOUS_CARD = "indigenous_card".freeze
    VEHICLE_REGISTRATION_CARD = "vehicle_registration_card".freeze
    CERTIFICATE_OF_NATURALISATION = "certificate_of_naturalisation".freeze
    PROFESSIONAL_QUALIFICATION_CARD = "professional_qualification_card".freeze
    CONSULAR_ID = "consular_id".freeze
    INTERNATIONAL_DRIVING_LICENCE = "international_driving_licence".freeze
    HOME_OFFICE_LETTER = "home_office_letter".freeze
    BIRTH_CERTIFICATE = "birth_certificate".freeze
    VEHICLE_REGISTRATION_CERTIFICATE = "vehicle_registration_certificate".freeze
    FORM_FOR_AFFIXING_THE_VISA = "form_for_affixing_the_visa".freeze
    IDENTIFICATION_NUMBER_DOCUMENT = "identification_number_document".freeze
    ADOPTION_CERTIFICATE = "adoption_certificate".freeze
    BANK_BUILDING_SOCIETY_STATEMENT = "bank_building_society_statement".freeze
    BANK_STATEMENT = "bank_statement".freeze
    BENEFIT_LETTERS = "benefit_letters".freeze
    CBT = "cbt".freeze
    CERTIFICATE_OF_SPONSORSHIP = "certificate_of_sponsorship".freeze
    CHARACTER_REFERENCE = "character_reference".freeze
    CIVIL_PARTNERSHIP_CERTIFICATE = "civil_partnership_certificate".freeze
    COUNCIL_TAX = "council_tax".freeze
    CREDIT_CARD_STATEMENT = "credit_card_statement".freeze
    DEED_POLL = "deed_poll".freeze
    DIVORCE_ABSOLUTE_DECREE = "divorce_absolute_decree".freeze
    EDUCATIONAL_STATEMENT = "educational_statement".freeze
    ELECTRICITY_BILL = "electricity_bill".freeze
    GAS_BILL = "gas_bill".freeze
    GOVERNMENT_LETTER = "government_letter".freeze
    INTERNET_BILL = "internet_bill".freeze
    MARRIAGE_CERTIFICATE = "marriage_certificate".freeze
    MOTORCYCLE_INSURANCE = "motorcycle_insurance".freeze
    NATIONAL_INSURANCE_CARD = "national_insurance_card".freeze
    NATURALISATION_CERTIFICATE = "naturalisation_certificate".freeze
    NON_UK_DRIVING_LICENCE = "non_uk_driving_licence".freeze
    P45_P60 = "p45_p60".freeze
    PAYSLIP = "payslip".freeze
    PHONE_BILL = "phone_bill".freeze
    PROFESSIONAL_IDENTIFICATION_CARD = "professional_identification_card".freeze
    RIGHT_TO_WORK_SHARE_CODE_RESULT = "right_to_work_share_code_result".freeze
    STATEMENT_FACT = "statement_fact".freeze
    T4_STUDENT_UNIVERSITY_TERM_DATES_EVIDENCE = "t4_student_university_term_dates_evidence".freeze
    UK_BIOMETRIC_RESIDENCE_PERMIT = "uk_biometric_residence_permit".freeze
    UK_DRIVING_LICENCE = "uk_driving_licence".freeze
    UNKNOWN = "unknown".freeze
    UTILITY_BILL = "utility_bill".freeze
    UTILITY_BILL_ELECTRIC = "utility_bill_electric".freeze
    UTILITY_BILL_GAS = "utility_bill_gas".freeze
    UTILITY_BILL_OTHER = "utility_bill_other".freeze
    WATER_BILL = "water_bill".freeze
    ADDRESS_CERTIFICATE = "address_certificate".freeze
    GENERAL_LETTER = "general_letter".freeze
    INSURANCE_STATEMENT = "insurance_statement".freeze
    PENSION_PROPERTY_STATEMENT_LETTER = "pension_property_statement_letter".freeze
    MORTGAGE_STATEMENT = "mortgage_statement".freeze
    MOBILE_PHONE_BILL = "mobile_phone_bill".freeze
    IDENTITY_DOCUMENT_WITH_ADDRESS = "identity_document_with_address".freeze
    EXCHANGE_HOUSE_STATEMENT = "exchange_house_statement".freeze
    ACCOMMODATION_TENANCY_CERTIFICATE = "accommodation_tenancy_certificate".freeze
    UNKNOWN_DEFAULT_OPEN_API = "unknown_default_open_api".freeze

    def self.all_vars
      @all_vars ||= [PASSPORT, DRIVING_LICENCE, NATIONAL_IDENTITY_CARD, RESIDENCE_PERMIT, PASSPORT_CARD, TAX_ID, VISA, VOTER_ID, RESIDENCE_STATUS_DOCUMENT, POSTAL_IDENTITY_CARD, SOCIAL_SECURITY_CARD, WORK_PERMIT, ASYLUM_REGISTRATION_CARD, NATIONAL_HEALTH_INSURANCE_CARD, MUNICIPALITY_IDENTITY_CARD, PRIVATE_OPERATORS_CARD, PROOF_OF_CITIZENSHIP, SERVICE_ID_CARD, IMMIGRATION_STATUS_DOCUMENT, INDIGENOUS_CARD, VEHICLE_REGISTRATION_CARD, CERTIFICATE_OF_NATURALISATION, PROFESSIONAL_QUALIFICATION_CARD, CONSULAR_ID, INTERNATIONAL_DRIVING_LICENCE, HOME_OFFICE_LETTER, BIRTH_CERTIFICATE, VEHICLE_REGISTRATION_CERTIFICATE, FORM_FOR_AFFIXING_THE_VISA, IDENTIFICATION_NUMBER_DOCUMENT, ADOPTION_CERTIFICATE, BANK_BUILDING_SOCIETY_STATEMENT, BANK_STATEMENT, BENEFIT_LETTERS, CBT, CERTIFICATE_OF_SPONSORSHIP, CHARACTER_REFERENCE, CIVIL_PARTNERSHIP_CERTIFICATE, COUNCIL_TAX, CREDIT_CARD_STATEMENT, DEED_POLL, DIVORCE_ABSOLUTE_DECREE, EDUCATIONAL_STATEMENT, ELECTRICITY_BILL, GAS_BILL, GOVERNMENT_LETTER, INTERNET_BILL, MARRIAGE_CERTIFICATE, MOTORCYCLE_INSURANCE, NATIONAL_INSURANCE_CARD, NATURALISATION_CERTIFICATE, NON_UK_DRIVING_LICENCE, P45_P60, PAYSLIP, PHONE_BILL, PROFESSIONAL_IDENTIFICATION_CARD, RIGHT_TO_WORK_SHARE_CODE_RESULT, STATEMENT_FACT, T4_STUDENT_UNIVERSITY_TERM_DATES_EVIDENCE, UK_BIOMETRIC_RESIDENCE_PERMIT, UK_DRIVING_LICENCE, UNKNOWN, UTILITY_BILL, UTILITY_BILL_ELECTRIC, UTILITY_BILL_GAS, UTILITY_BILL_OTHER, WATER_BILL, ADDRESS_CERTIFICATE, GENERAL_LETTER, INSURANCE_STATEMENT, PENSION_PROPERTY_STATEMENT_LETTER, MORTGAGE_STATEMENT, MOBILE_PHONE_BILL, IDENTITY_DOCUMENT_WITH_ADDRESS, EXCHANGE_HOUSE_STATEMENT, ACCOMMODATION_TENANCY_CERTIFICATE, UNKNOWN_DEFAULT_OPEN_API].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DocumentTypes.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DocumentTypes"
    end
  end
end
