=begin
#Onfido Public API v3.6

#The Onfido Public API (v3.6)

The version of the OpenAPI document: v3.6

Generated by: https://openapi-generator.tech
Generator version: 7.16.0

=end

require 'date'
require 'time'

module Onfido
  class WatchlistMeshRiskDecision
    NOT_REVIEWED = "NOT_REVIEWED".freeze
    IN_REVIEW = "IN_REVIEW".freeze
    FALSE_POSITIVE = "FALSE_POSITIVE".freeze
    TRUE_POSITIVE = "TRUE_POSITIVE".freeze
    UNKNOWN_DEFAULT_OPEN_API = "unknown_default_open_api".freeze

    def self.all_vars
      @all_vars ||= [NOT_REVIEWED, IN_REVIEW, FALSE_POSITIVE, TRUE_POSITIVE, UNKNOWN_DEFAULT_OPEN_API].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WatchlistMeshRiskDecision.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WatchlistMeshRiskDecision"
    end
  end
end
