=begin
#Onfido API v3.6

#The Onfido API (v3.6)

The version of the OpenAPI document: v3.6

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Onfido
  class WebhookEventObjectStatus
    PROCESSING = "processing".freeze
    AWAITING_INPUT = "awaiting_input".freeze
    AWAITING_CLIENT_INPUT = "awaiting_client_input".freeze
    APPROVED = "approved".freeze
    DECLINED = "declined".freeze
    REVIEW = "review".freeze
    ABANDONED = "abandoned".freeze
    ERROR = "error".freeze
    STARTED = "started".freeze
    CANCELLED = "cancelled".freeze
    COMPLETED = "completed".freeze
    AWAITING_DATA = "awaiting_data".freeze
    AWAITING_APPROVAL = "awaiting_approval".freeze
    COMPLETE = "complete".freeze
    WITHDRAWN = "withdrawn".freeze
    IN_PROGRESS = "in_progress".freeze
    AWAITING_APPLICANT = "awaiting_applicant".freeze
    PAUSED = "paused".freeze
    REOPENED = "reopened".freeze
    UNKNOWN_DEFAULT_OPEN_API = "unknown_default_open_api".freeze

    def self.all_vars
      @all_vars ||= [PROCESSING, AWAITING_INPUT, AWAITING_CLIENT_INPUT, APPROVED, DECLINED, REVIEW, ABANDONED, ERROR, STARTED, CANCELLED, COMPLETED, AWAITING_DATA, AWAITING_APPROVAL, COMPLETE, WITHDRAWN, IN_PROGRESS, AWAITING_APPLICANT, PAUSED, REOPENED, UNKNOWN_DEFAULT_OPEN_API].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WebhookEventObjectStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WebhookEventObjectStatus"
    end
  end
end
